language: elixir
sudo: false

elixir: [1.4.4]
otp_release: 19.3

cache:
  directories:
    - $HOME/.mix

before_script:
  - mix eqc.install --mini || true

script:
  - mix format --check-formatted
  - mix test
  - mix credo --strict
