language: elixir
sudo: false

elixir:
  - 1.6

otp_release:
  - 19.3
  - 20.1

cache:
  directories:
    - $HOME/.mix

before_script:
  - mix eqc.install --mini || true

script:
  - mix format --check-formatted
  - mix test
  - mix credo --strict
